#!/usr/bin/env bash

# Set max brightness for laptop screen
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
echo "${max_brightness}" > /sys/class/backlight/intel_backlight/brightness

# Adjust DPI of displays
xrandr --dpi 96 --output eDP-1 --scale 0.5x0.5 --output DP-3-2 --scale 1x1

# Start screensaver
xautolock -time 5 -locker /usr/local/bin/i3lock-fancy &

# Start graphical program launcher
albert &

# Bluetooth configuration
/usr/local/bin/bluetooth-trackpad

# Start window manager
export TERMINAL="mate-terminal"
exec i3
